### ISSUE TITLE
Implement public API

### ISSUE THREAD

**Issue by olabini** [twstrike/otr3#19]

**Comment by olabini** [comment]
Specifically, this is primarily:
type Conversation
    func (c *Conversation) Authenticate(question string, mutualSecret []byte) (toSend [][]byte, err error)
    func (c *Conversation) End() (toSend [][]byte)
    func (c *Conversation) IsEncrypted() bool
    func (c *Conversation) Receive(in []byte) (out []byte, encrypted bool, change SecurityChange, toSend [][]byte, err error)
    func (c *Conversation) SMPQuestion() string
    func (c *Conversation) Send(msg []byte) ([][]byte, error)

**Comment by juniorz** [comment]
This is what I have in mind: we don't necessarily need to make our public API the same as golang's otr (specially because I suspect, agl's xmpp-client might be the only consumer for this).

That's why I thought about having a facade exported `Conversation` (potentially in a separate package) that provides this public API. This allows us to have whatever API fits better our design goals (channels, maybe?) as long as providing proper defaults for things the golang implementation does not have (policy, for example).

Porting a project that currently uses golang's otr could be as simple as replacing `import "golang.org/x/crypto/otr"` by `import otr "github.com/twstrike/otr3/compat"`

**Comment by tcz001** [comment]
Agree, if there are some places we don't think is doing right, like exporting TheirPublicKey and PrivateKey at our conversation level. Let's have a subpack compat for current API

**Comment by olabini** [comment]
Agreed.

**Comment by tdruiva** [comment]
![image](http://i.giphy.com/jOAr0ZeFwzG6s.gif)

**Comment by olabini** [comment]
This is basically done.
